### ISSUE TITLE
Is consul support deprecated?

### ISSUE THREAD

**Issue by nicgrayson** [ceph/ceph-docker#533]
I was working on deploying ceph using consul as my KV when I started getting messages in the log indicating that it was trying to use a static config instead:

```
2017-03-08 22:25:41  /entrypoint.sh: static: does not generate config
2017-03-08 22:25:41  /entrypoint.sh: ERROR- /etc/ceph/ceph.conf must exist; get it from your existing mon
```

It seemed like from the discussion on #497 that consul support might be going away but there has been no update to any docs to that affect.

**Comment by leseb** [comment]
Sorry about that. I just pushed a commit to clarify this. https://github.com/ceph/ceph-docker/pull/540

**Comment by softwarevamp** [comment]
still exists in Windows docker -v

`docker create -v /dev --name dev ceph/daemon
docker create -v /dev/sdb --name sdb ceph/daemon

docker rm -f osd & docker run -d --net=host --name=osd^
 --privileged=true^
 --volumes-from etc --volumes-from=lib^
 --volumes-from dev --volumes-from=sdb^
 -e OSD_DEVICE=/dev/sdb^
 ceph/daemon osd_ceph_disk
docker logs -f osd
`
